# coding: utf-8

"""
    PreForm API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from formlabs.models.scene_auto_orient_post_request import SceneAutoOrientPostRequest

class TestSceneAutoOrientPostRequest(unittest.TestCase):
    """SceneAutoOrientPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SceneAutoOrientPostRequest:
        """Test SceneAutoOrientPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SceneAutoOrientPostRequest`
        """
        model = SceneAutoOrientPostRequest()
        if include_optional:
            return SceneAutoOrientPostRequest(
                models = formlabs.models.models_selection_model.ModelsSelectionModel(
                    models = null, )
            )
        else:
            return SceneAutoOrientPostRequest(
                models = formlabs.models.models_selection_model.ModelsSelectionModel(
                    models = null, ),
        )
        """

    def testSceneAutoOrientPostRequest(self):
        """Test SceneAutoOrientPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
