# coding: utf-8

"""
    PreForm API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from formlabs.models.scene_models_id_replace_post200_response import SceneModelsIdReplacePost200Response

class TestSceneModelsIdReplacePost200Response(unittest.TestCase):
    """SceneModelsIdReplacePost200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SceneModelsIdReplacePost200Response:
        """Test SceneModelsIdReplacePost200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SceneModelsIdReplacePost200Response`
        """
        model = SceneModelsIdReplacePost200Response()
        if include_optional:
            return SceneModelsIdReplacePost200Response(
                id = ''
            )
        else:
            return SceneModelsIdReplacePost200Response(
        )
        """

    def testSceneModelsIdReplacePost200Response(self):
        """Test SceneModelsIdReplacePost200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
