/**
 * PreForm API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import AutoLayoutPost500Response from './model/AutoLayoutPost500Response';
import AutoOrientPostRequest from './model/AutoOrientPostRequest';
import AutoOrientPostRequestModels from './model/AutoOrientPostRequestModels';
import ExportPost200Response from './model/ExportPost200Response';
import ImportModelPost200Response from './model/ImportModelPost200Response';
import ScenePostRequest from './model/ScenePostRequest';
import V1PrintPost200Response from './model/V1PrintPost200Response';
import DefaultApi from './api/DefaultApi';


/**
* JS API client generated by OpenAPI Generator.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var PreFormApi = require('index'); // See note below*.
* var xxxSvc = new PreFormApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new PreFormApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new PreFormApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new PreFormApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AutoLayoutPost500Response model constructor.
     * @property {module:model/AutoLayoutPost500Response}
     */
    AutoLayoutPost500Response,

    /**
     * The AutoOrientPostRequest model constructor.
     * @property {module:model/AutoOrientPostRequest}
     */
    AutoOrientPostRequest,

    /**
     * The AutoOrientPostRequestModels model constructor.
     * @property {module:model/AutoOrientPostRequestModels}
     */
    AutoOrientPostRequestModels,

    /**
     * The ExportPost200Response model constructor.
     * @property {module:model/ExportPost200Response}
     */
    ExportPost200Response,

    /**
     * The ImportModelPost200Response model constructor.
     * @property {module:model/ImportModelPost200Response}
     */
    ImportModelPost200Response,

    /**
     * The ScenePostRequest model constructor.
     * @property {module:model/ScenePostRequest}
     */
    ScenePostRequest,

    /**
     * The V1PrintPost200Response model constructor.
     * @property {module:model/V1PrintPost200Response}
     */
    V1PrintPost200Response,

    /**
    * The DefaultApi service constructor.
    * @property {module:api/DefaultApi}
    */
    DefaultApi
};
