/**
 * PreForm API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ModelsSelectionModel from './ModelsSelectionModel';

/**
 * The AutoOrientPostRequest model module.
 * @module model/AutoOrientPostRequest
 * @version 1.0
 */
class AutoOrientPostRequest {
    /**
     * Constructs a new <code>AutoOrientPostRequest</code>.
     * @alias module:model/AutoOrientPostRequest
     * @param models {module:model/ModelsSelectionModel} 
     */
    constructor(models) { 
        
        AutoOrientPostRequest.initialize(this, models);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, models) { 
        obj['models'] = models;
    }

    /**
     * Constructs a <code>AutoOrientPostRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AutoOrientPostRequest} obj Optional instance to populate.
     * @return {module:model/AutoOrientPostRequest} The populated <code>AutoOrientPostRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AutoOrientPostRequest();

            if (data.hasOwnProperty('models')) {
                obj['models'] = ModelsSelectionModel.constructFromObject(data['models']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AutoOrientPostRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AutoOrientPostRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of AutoOrientPostRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `models`
        if (data['models']) { // data not null
          ModelsSelectionModel.validateJSON(data['models']);
        }

        return true;
    }


}

AutoOrientPostRequest.RequiredProperties = ["models"];

/**
 * @member {module:model/ModelsSelectionModel} models
 */
AutoOrientPostRequest.prototype['models'] = undefined;






export default AutoOrientPostRequest;

