/**
 * PreForm API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import FleetControlPrinterGroup from './FleetControlPrinterGroup';
import Form2Printer from './Form2Printer';
import Form3Printer from './Form3Printer';
import Form4Printer from './Form4Printer';
import Form4PrinterCartridgeDataValue from './Form4PrinterCartridgeDataValue';
import Fuse11Printer from './Fuse11Printer';
import GenericDevice from './GenericDevice';

/**
 * The DeviceStatusModel model module.
 * @module model/DeviceStatusModel
 * @version 1.0
 */
class DeviceStatusModel {
    /**
     * Constructs a new <code>DeviceStatusModel</code>.
     * @alias module:model/DeviceStatusModel
     * @param {(module:model/FleetControlPrinterGroup|module:model/Form2Printer|module:model/Form3Printer|module:model/Form4Printer|module:model/Fuse11Printer|module:model/GenericDevice)} instance The actual instance to initialize DeviceStatusModel.
     */
    constructor(instance = null) {
        if (instance === null) {
            this.actualInstance = null;
            return;
        }
        var match = 0;
        var errorMessages = [];
        try {
            if (typeof instance === "GenericDevice") {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                GenericDevice.validateJSON(instance); // throw an exception if no match
                // create GenericDevice from JS object
                this.actualInstance = GenericDevice.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into GenericDevice
            errorMessages.push("Failed to construct GenericDevice: " + err)
        }

        try {
            if (typeof instance === "FleetControlPrinterGroup") {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                FleetControlPrinterGroup.validateJSON(instance); // throw an exception if no match
                // create FleetControlPrinterGroup from JS object
                this.actualInstance = FleetControlPrinterGroup.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into FleetControlPrinterGroup
            errorMessages.push("Failed to construct FleetControlPrinterGroup: " + err)
        }

        try {
            if (typeof instance === "Form4Printer") {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                Form4Printer.validateJSON(instance); // throw an exception if no match
                // create Form4Printer from JS object
                this.actualInstance = Form4Printer.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into Form4Printer
            errorMessages.push("Failed to construct Form4Printer: " + err)
        }

        try {
            if (typeof instance === "Form3Printer") {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                Form3Printer.validateJSON(instance); // throw an exception if no match
                // create Form3Printer from JS object
                this.actualInstance = Form3Printer.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into Form3Printer
            errorMessages.push("Failed to construct Form3Printer: " + err)
        }

        try {
            if (typeof instance === "Fuse11Printer") {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                Fuse11Printer.validateJSON(instance); // throw an exception if no match
                // create Fuse11Printer from JS object
                this.actualInstance = Fuse11Printer.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into Fuse11Printer
            errorMessages.push("Failed to construct Fuse11Printer: " + err)
        }

        try {
            if (typeof instance === "Form2Printer") {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                Form2Printer.validateJSON(instance); // throw an exception if no match
                // create Form2Printer from JS object
                this.actualInstance = Form2Printer.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into Form2Printer
            errorMessages.push("Failed to construct Form2Printer: " + err)
        }

        if (match > 1) {
            throw new Error("Multiple matches found constructing `DeviceStatusModel` with oneOf schemas FleetControlPrinterGroup, Form2Printer, Form3Printer, Form4Printer, Fuse11Printer, GenericDevice. Input: " + JSON.stringify(instance));
        } else if (match === 0) {
            this.actualInstance = null; // clear the actual instance in case there are multiple matches
            throw new Error("No match found constructing `DeviceStatusModel` with oneOf schemas FleetControlPrinterGroup, Form2Printer, Form3Printer, Form4Printer, Fuse11Printer, GenericDevice. Details: " +
                            errorMessages.join(", "));
        } else { // only 1 match
            // the input is valid
        }
    }

    /**
     * Constructs a <code>DeviceStatusModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DeviceStatusModel} obj Optional instance to populate.
     * @return {module:model/DeviceStatusModel} The populated <code>DeviceStatusModel</code> instance.
     */
    static constructFromObject(data, obj) {
        return new DeviceStatusModel(data);
    }

    /**
     * Gets the actual instance, which can be <code>FleetControlPrinterGroup</code>, <code>Form2Printer</code>, <code>Form3Printer</code>, <code>Form4Printer</code>, <code>Fuse11Printer</code>, <code>GenericDevice</code>.
     * @return {(module:model/FleetControlPrinterGroup|module:model/Form2Printer|module:model/Form3Printer|module:model/Form4Printer|module:model/Fuse11Printer|module:model/GenericDevice)} The actual instance.
     */
    getActualInstance() {
        return this.actualInstance;
    }

    /**
     * Sets the actual instance, which can be <code>FleetControlPrinterGroup</code>, <code>Form2Printer</code>, <code>Form3Printer</code>, <code>Form4Printer</code>, <code>Fuse11Printer</code>, <code>GenericDevice</code>.
     * @param {(module:model/FleetControlPrinterGroup|module:model/Form2Printer|module:model/Form3Printer|module:model/Form4Printer|module:model/Fuse11Printer|module:model/GenericDevice)} obj The actual instance.
     */
    setActualInstance(obj) {
       this.actualInstance = DeviceStatusModel.constructFromObject(obj).getActualInstance();
    }

    /**
     * Returns the JSON representation of the actual instance.
     * @return {string}
     */
    toJSON = function(){
        return this.getActualInstance();
    }

    /**
     * Create an instance of DeviceStatusModel from a JSON string.
     * @param {string} json_string JSON string.
     * @return {module:model/DeviceStatusModel} An instance of DeviceStatusModel.
     */
    static fromJSON = function(json_string){
        return DeviceStatusModel.constructFromObject(JSON.parse(json_string));
    }
}

/**
 * @member {String} id
 */
DeviceStatusModel.prototype['id'] = undefined;

/**
 * @member {String} product_name
 */
DeviceStatusModel.prototype['product_name'] = undefined;

/**
 * @member {String} status
 */
DeviceStatusModel.prototype['status'] = undefined;

/**
 * @member {Boolean} is_connected
 */
DeviceStatusModel.prototype['is_connected'] = undefined;

/**
 * @member {module:model/DeviceStatusModel.ConnectionTypeEnum} connection_type
 */
DeviceStatusModel.prototype['connection_type'] = undefined;

/**
 * @member {String} ip_address
 */
DeviceStatusModel.prototype['ip_address'] = undefined;

/**
 * @member {String} firmware_version
 */
DeviceStatusModel.prototype['firmware_version'] = undefined;

/**
 * @member {String} dashboard_group_id
 */
DeviceStatusModel.prototype['dashboard_group_id'] = undefined;

/**
 * @member {String} dashboard_queue_id
 */
DeviceStatusModel.prototype['dashboard_queue_id'] = undefined;

/**
 * @member {Boolean} is_remote_print_enabled
 */
DeviceStatusModel.prototype['is_remote_print_enabled'] = undefined;

/**
 * @member {Number} estimated_print_time_remaining_ms
 */
DeviceStatusModel.prototype['estimated_print_time_remaining_ms'] = undefined;

/**
 * @member {String} tank_id
 */
DeviceStatusModel.prototype['tank_id'] = undefined;

/**
 * @member {String} tank_material_code
 */
DeviceStatusModel.prototype['tank_material_code'] = undefined;

/**
 * @member {Object.<String, module:model/Form4PrinterCartridgeDataValue>} cartridge_data
 */
DeviceStatusModel.prototype['cartridge_data'] = undefined;

/**
 * @member {Boolean} ready_to_print_now
 */
DeviceStatusModel.prototype['ready_to_print_now'] = undefined;

/**
 * @member {String} form_auto_status
 */
DeviceStatusModel.prototype['form_auto_status'] = undefined;

/**
 * @member {Number} bed_temperature_c
 */
DeviceStatusModel.prototype['bed_temperature_c'] = undefined;

/**
 * @member {String} powder_level
 */
DeviceStatusModel.prototype['powder_level'] = undefined;

/**
 * @member {Number} printing_layer
 */
DeviceStatusModel.prototype['printing_layer'] = undefined;

/**
 * @member {String} printing_guid
 */
DeviceStatusModel.prototype['printing_guid'] = undefined;

/**
 * @member {String} cylinder_material_code
 */
DeviceStatusModel.prototype['cylinder_material_code'] = undefined;

/**
 * @member {String} cylinder_serial
 */
DeviceStatusModel.prototype['cylinder_serial'] = undefined;

/**
 * @member {String} printer_material_code
 */
DeviceStatusModel.prototype['printer_material_code'] = undefined;

/**
 * @member {Number} powder_credit_g
 */
DeviceStatusModel.prototype['powder_credit_g'] = undefined;


DeviceStatusModel.OneOf = ["FleetControlPrinterGroup", "Form2Printer", "Form3Printer", "Form4Printer", "Fuse11Printer", "GenericDevice"];

export default DeviceStatusModel;

