/**
 * PreForm API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DiscoverDevicesPostRequest model module.
 * @module model/DiscoverDevicesPostRequest
 * @version 1.0
 */
class DiscoverDevicesPostRequest {
    /**
     * Constructs a new <code>DiscoverDevicesPostRequest</code>.
     * @alias module:model/DiscoverDevicesPostRequest
     */
    constructor() { 
        
        DiscoverDevicesPostRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DiscoverDevicesPostRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DiscoverDevicesPostRequest} obj Optional instance to populate.
     * @return {module:model/DiscoverDevicesPostRequest} The populated <code>DiscoverDevicesPostRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DiscoverDevicesPostRequest();

            if (data.hasOwnProperty('timeout_seconds')) {
                obj['timeout_seconds'] = ApiClient.convertToType(data['timeout_seconds'], 'Number');
            }
            if (data.hasOwnProperty('ip_address')) {
                obj['ip_address'] = ApiClient.convertToType(data['ip_address'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DiscoverDevicesPostRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DiscoverDevicesPostRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['ip_address'] && !(typeof data['ip_address'] === 'string' || data['ip_address'] instanceof String)) {
            throw new Error("Expected the field `ip_address` to be a primitive type in the JSON string but got " + data['ip_address']);
        }

        return true;
    }


}



/**
 * Number of seconds to wait when discovering devices
 * @member {Number} timeout_seconds
 */
DiscoverDevicesPostRequest.prototype['timeout_seconds'] = undefined;

/**
 * Local network IP address to attempt to discover a device at
 * @member {String} ip_address
 */
DiscoverDevicesPostRequest.prototype['ip_address'] = undefined;






export default DiscoverDevicesPostRequest;

