/**
 * PreForm API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The EstimatedPrintTimeModel model module.
 * @module model/EstimatedPrintTimeModel
 * @version 1.0
 */
class EstimatedPrintTimeModel {
    /**
     * Constructs a new <code>EstimatedPrintTimeModel</code>.
     * @alias module:model/EstimatedPrintTimeModel
     */
    constructor() { 
        
        EstimatedPrintTimeModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>EstimatedPrintTimeModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EstimatedPrintTimeModel} obj Optional instance to populate.
     * @return {module:model/EstimatedPrintTimeModel} The populated <code>EstimatedPrintTimeModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EstimatedPrintTimeModel();

            if (data.hasOwnProperty('total_print_time_s')) {
                obj['total_print_time_s'] = ApiClient.convertToType(data['total_print_time_s'], 'Number');
            }
            if (data.hasOwnProperty('preprint_time_s')) {
                obj['preprint_time_s'] = ApiClient.convertToType(data['preprint_time_s'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>EstimatedPrintTimeModel</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>EstimatedPrintTimeModel</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Number} total_print_time_s
 */
EstimatedPrintTimeModel.prototype['total_print_time_s'] = undefined;

/**
 * @member {Number} preprint_time_s
 */
EstimatedPrintTimeModel.prototype['preprint_time_s'] = undefined;






export default EstimatedPrintTimeModel;

