/**
 * PreForm API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The EulerAnglesModel model module.
 * @module model/EulerAnglesModel
 * @version 1.0
 */
class EulerAnglesModel {
    /**
     * Constructs a new <code>EulerAnglesModel</code>.
     * Orientation specified using Euler angles in radians. TODO applied in what order, in which direction? What axis has worst gimbal lock?
     * @alias module:model/EulerAnglesModel
     * @param x {Number} Euler angle x rotation
     * @param y {Number} Euler angle y rotation
     * @param z {Number} Euler angle z rotation
     */
    constructor(x, y, z) { 
        
        EulerAnglesModel.initialize(this, x, y, z);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, x, y, z) { 
        obj['x'] = x;
        obj['y'] = y;
        obj['z'] = z;
    }

    /**
     * Constructs a <code>EulerAnglesModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EulerAnglesModel} obj Optional instance to populate.
     * @return {module:model/EulerAnglesModel} The populated <code>EulerAnglesModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EulerAnglesModel();

            if (data.hasOwnProperty('x')) {
                obj['x'] = ApiClient.convertToType(data['x'], 'Number');
            }
            if (data.hasOwnProperty('y')) {
                obj['y'] = ApiClient.convertToType(data['y'], 'Number');
            }
            if (data.hasOwnProperty('z')) {
                obj['z'] = ApiClient.convertToType(data['z'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>EulerAnglesModel</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>EulerAnglesModel</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of EulerAnglesModel.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

EulerAnglesModel.RequiredProperties = ["x", "y", "z"];

/**
 * Euler angle x rotation
 * @member {Number} x
 */
EulerAnglesModel.prototype['x'] = undefined;

/**
 * Euler angle y rotation
 * @member {Number} y
 */
EulerAnglesModel.prototype['y'] = undefined;

/**
 * Euler angle z rotation
 * @member {Number} z
 */
EulerAnglesModel.prototype['z'] = undefined;






export default EulerAnglesModel;

