/**
 * PreForm API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The FleetControlPrinterGroup model module.
 * @module model/FleetControlPrinterGroup
 * @version 1.0
 */
class FleetControlPrinterGroup {
    /**
     * Constructs a new <code>FleetControlPrinterGroup</code>.
     * @alias module:model/FleetControlPrinterGroup
     * @param id {String} 
     * @param productName {String} 
     * @param status {String} 
     * @param isConnected {Boolean} 
     * @param connectionType {module:model/FleetControlPrinterGroup.ConnectionTypeEnum} 
     * @param firmwareVersion {String} 
     * @param dashboardGroupId {String} 
     * @param dashboardQueueId {String} 
     */
    constructor(id, productName, status, isConnected, connectionType, firmwareVersion, dashboardGroupId, dashboardQueueId) { 
        
        FleetControlPrinterGroup.initialize(this, id, productName, status, isConnected, connectionType, firmwareVersion, dashboardGroupId, dashboardQueueId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, productName, status, isConnected, connectionType, firmwareVersion, dashboardGroupId, dashboardQueueId) { 
        obj['id'] = id;
        obj['product_name'] = productName;
        obj['status'] = status;
        obj['is_connected'] = isConnected;
        obj['connection_type'] = connectionType;
        obj['firmware_version'] = firmwareVersion;
        obj['dashboard_group_id'] = dashboardGroupId;
        obj['dashboard_queue_id'] = dashboardQueueId;
    }

    /**
     * Constructs a <code>FleetControlPrinterGroup</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FleetControlPrinterGroup} obj Optional instance to populate.
     * @return {module:model/FleetControlPrinterGroup} The populated <code>FleetControlPrinterGroup</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FleetControlPrinterGroup();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('product_name')) {
                obj['product_name'] = ApiClient.convertToType(data['product_name'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('is_connected')) {
                obj['is_connected'] = ApiClient.convertToType(data['is_connected'], 'Boolean');
            }
            if (data.hasOwnProperty('connection_type')) {
                obj['connection_type'] = ApiClient.convertToType(data['connection_type'], 'String');
            }
            if (data.hasOwnProperty('firmware_version')) {
                obj['firmware_version'] = ApiClient.convertToType(data['firmware_version'], 'String');
            }
            if (data.hasOwnProperty('dashboard_group_id')) {
                obj['dashboard_group_id'] = ApiClient.convertToType(data['dashboard_group_id'], 'String');
            }
            if (data.hasOwnProperty('dashboard_queue_id')) {
                obj['dashboard_queue_id'] = ApiClient.convertToType(data['dashboard_queue_id'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>FleetControlPrinterGroup</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>FleetControlPrinterGroup</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of FleetControlPrinterGroup.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['product_name'] && !(typeof data['product_name'] === 'string' || data['product_name'] instanceof String)) {
            throw new Error("Expected the field `product_name` to be a primitive type in the JSON string but got " + data['product_name']);
        }
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }
        // ensure the json data is a string
        if (data['connection_type'] && !(typeof data['connection_type'] === 'string' || data['connection_type'] instanceof String)) {
            throw new Error("Expected the field `connection_type` to be a primitive type in the JSON string but got " + data['connection_type']);
        }
        // ensure the json data is a string
        if (data['firmware_version'] && !(typeof data['firmware_version'] === 'string' || data['firmware_version'] instanceof String)) {
            throw new Error("Expected the field `firmware_version` to be a primitive type in the JSON string but got " + data['firmware_version']);
        }
        // ensure the json data is a string
        if (data['dashboard_group_id'] && !(typeof data['dashboard_group_id'] === 'string' || data['dashboard_group_id'] instanceof String)) {
            throw new Error("Expected the field `dashboard_group_id` to be a primitive type in the JSON string but got " + data['dashboard_group_id']);
        }
        // ensure the json data is a string
        if (data['dashboard_queue_id'] && !(typeof data['dashboard_queue_id'] === 'string' || data['dashboard_queue_id'] instanceof String)) {
            throw new Error("Expected the field `dashboard_queue_id` to be a primitive type in the JSON string but got " + data['dashboard_queue_id']);
        }

        return true;
    }


}

FleetControlPrinterGroup.RequiredProperties = ["id", "product_name", "status", "is_connected", "connection_type", "firmware_version", "dashboard_group_id", "dashboard_queue_id"];

/**
 * @member {String} id
 */
FleetControlPrinterGroup.prototype['id'] = undefined;

/**
 * @member {String} product_name
 */
FleetControlPrinterGroup.prototype['product_name'] = undefined;

/**
 * @member {String} status
 */
FleetControlPrinterGroup.prototype['status'] = undefined;

/**
 * @member {Boolean} is_connected
 */
FleetControlPrinterGroup.prototype['is_connected'] = undefined;

/**
 * @member {module:model/FleetControlPrinterGroup.ConnectionTypeEnum} connection_type
 */
FleetControlPrinterGroup.prototype['connection_type'] = undefined;

/**
 * @member {String} firmware_version
 */
FleetControlPrinterGroup.prototype['firmware_version'] = undefined;

/**
 * @member {String} dashboard_group_id
 */
FleetControlPrinterGroup.prototype['dashboard_group_id'] = undefined;

/**
 * @member {String} dashboard_queue_id
 */
FleetControlPrinterGroup.prototype['dashboard_queue_id'] = undefined;





/**
 * Allowed values for the <code>connection_type</code> property.
 * @enum {String}
 * @readonly
 */
FleetControlPrinterGroup['ConnectionTypeEnum'] = {

    /**
     * value: "REMOTE"
     * @const
     */
    "REMOTE": "REMOTE"
};



export default FleetControlPrinterGroup;

