/**
 * PreForm API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Fuse11Printer model module.
 * @module model/Fuse11Printer
 * @version 1.0
 */
class Fuse11Printer {
    /**
     * Constructs a new <code>Fuse11Printer</code>.
     * @alias module:model/Fuse11Printer
     * @param id {String} 
     * @param productName {String} 
     * @param status {String} 
     * @param isConnected {Boolean} 
     * @param connectionType {module:model/Fuse11Printer.ConnectionTypeEnum} 
     * @param ipAddress {String} 
     * @param firmwareVersion {String} 
     * @param isRemotePrintEnabled {Boolean} 
     * @param estimatedPrintTimeRemainingMs {Number} 
     * @param bedTemperatureC {Number} 
     * @param powderLevel {String} 
     * @param printingLayer {Number} 
     * @param printingGuid {String} 
     * @param cylinderMaterialCode {String} 
     * @param cylinderSerial {String} 
     * @param printerMaterialCode {String} 
     * @param powderCreditG {Number} 
     */
    constructor(id, productName, status, isConnected, connectionType, ipAddress, firmwareVersion, isRemotePrintEnabled, estimatedPrintTimeRemainingMs, bedTemperatureC, powderLevel, printingLayer, printingGuid, cylinderMaterialCode, cylinderSerial, printerMaterialCode, powderCreditG) { 
        
        Fuse11Printer.initialize(this, id, productName, status, isConnected, connectionType, ipAddress, firmwareVersion, isRemotePrintEnabled, estimatedPrintTimeRemainingMs, bedTemperatureC, powderLevel, printingLayer, printingGuid, cylinderMaterialCode, cylinderSerial, printerMaterialCode, powderCreditG);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, productName, status, isConnected, connectionType, ipAddress, firmwareVersion, isRemotePrintEnabled, estimatedPrintTimeRemainingMs, bedTemperatureC, powderLevel, printingLayer, printingGuid, cylinderMaterialCode, cylinderSerial, printerMaterialCode, powderCreditG) { 
        obj['id'] = id;
        obj['product_name'] = productName;
        obj['status'] = status;
        obj['is_connected'] = isConnected;
        obj['connection_type'] = connectionType;
        obj['ip_address'] = ipAddress;
        obj['firmware_version'] = firmwareVersion;
        obj['is_remote_print_enabled'] = isRemotePrintEnabled;
        obj['estimated_print_time_remaining_ms'] = estimatedPrintTimeRemainingMs;
        obj['bed_temperature_c'] = bedTemperatureC;
        obj['powder_level'] = powderLevel;
        obj['printing_layer'] = printingLayer;
        obj['printing_guid'] = printingGuid;
        obj['cylinder_material_code'] = cylinderMaterialCode;
        obj['cylinder_serial'] = cylinderSerial;
        obj['printer_material_code'] = printerMaterialCode;
        obj['powder_credit_g'] = powderCreditG;
    }

    /**
     * Constructs a <code>Fuse11Printer</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Fuse11Printer} obj Optional instance to populate.
     * @return {module:model/Fuse11Printer} The populated <code>Fuse11Printer</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Fuse11Printer();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('product_name')) {
                obj['product_name'] = ApiClient.convertToType(data['product_name'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('is_connected')) {
                obj['is_connected'] = ApiClient.convertToType(data['is_connected'], 'Boolean');
            }
            if (data.hasOwnProperty('connection_type')) {
                obj['connection_type'] = ApiClient.convertToType(data['connection_type'], 'String');
            }
            if (data.hasOwnProperty('ip_address')) {
                obj['ip_address'] = ApiClient.convertToType(data['ip_address'], 'String');
            }
            if (data.hasOwnProperty('firmware_version')) {
                obj['firmware_version'] = ApiClient.convertToType(data['firmware_version'], 'String');
            }
            if (data.hasOwnProperty('is_remote_print_enabled')) {
                obj['is_remote_print_enabled'] = ApiClient.convertToType(data['is_remote_print_enabled'], 'Boolean');
            }
            if (data.hasOwnProperty('estimated_print_time_remaining_ms')) {
                obj['estimated_print_time_remaining_ms'] = ApiClient.convertToType(data['estimated_print_time_remaining_ms'], 'Number');
            }
            if (data.hasOwnProperty('bed_temperature_c')) {
                obj['bed_temperature_c'] = ApiClient.convertToType(data['bed_temperature_c'], 'Number');
            }
            if (data.hasOwnProperty('powder_level')) {
                obj['powder_level'] = ApiClient.convertToType(data['powder_level'], 'String');
            }
            if (data.hasOwnProperty('printing_layer')) {
                obj['printing_layer'] = ApiClient.convertToType(data['printing_layer'], 'Number');
            }
            if (data.hasOwnProperty('printing_guid')) {
                obj['printing_guid'] = ApiClient.convertToType(data['printing_guid'], 'String');
            }
            if (data.hasOwnProperty('cylinder_material_code')) {
                obj['cylinder_material_code'] = ApiClient.convertToType(data['cylinder_material_code'], 'String');
            }
            if (data.hasOwnProperty('cylinder_serial')) {
                obj['cylinder_serial'] = ApiClient.convertToType(data['cylinder_serial'], 'String');
            }
            if (data.hasOwnProperty('printer_material_code')) {
                obj['printer_material_code'] = ApiClient.convertToType(data['printer_material_code'], 'String');
            }
            if (data.hasOwnProperty('powder_credit_g')) {
                obj['powder_credit_g'] = ApiClient.convertToType(data['powder_credit_g'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Fuse11Printer</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Fuse11Printer</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of Fuse11Printer.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['product_name'] && !(typeof data['product_name'] === 'string' || data['product_name'] instanceof String)) {
            throw new Error("Expected the field `product_name` to be a primitive type in the JSON string but got " + data['product_name']);
        }
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }
        // ensure the json data is a string
        if (data['connection_type'] && !(typeof data['connection_type'] === 'string' || data['connection_type'] instanceof String)) {
            throw new Error("Expected the field `connection_type` to be a primitive type in the JSON string but got " + data['connection_type']);
        }
        // ensure the json data is a string
        if (data['ip_address'] && !(typeof data['ip_address'] === 'string' || data['ip_address'] instanceof String)) {
            throw new Error("Expected the field `ip_address` to be a primitive type in the JSON string but got " + data['ip_address']);
        }
        // ensure the json data is a string
        if (data['firmware_version'] && !(typeof data['firmware_version'] === 'string' || data['firmware_version'] instanceof String)) {
            throw new Error("Expected the field `firmware_version` to be a primitive type in the JSON string but got " + data['firmware_version']);
        }
        // ensure the json data is a string
        if (data['powder_level'] && !(typeof data['powder_level'] === 'string' || data['powder_level'] instanceof String)) {
            throw new Error("Expected the field `powder_level` to be a primitive type in the JSON string but got " + data['powder_level']);
        }
        // ensure the json data is a string
        if (data['printing_guid'] && !(typeof data['printing_guid'] === 'string' || data['printing_guid'] instanceof String)) {
            throw new Error("Expected the field `printing_guid` to be a primitive type in the JSON string but got " + data['printing_guid']);
        }
        // ensure the json data is a string
        if (data['cylinder_material_code'] && !(typeof data['cylinder_material_code'] === 'string' || data['cylinder_material_code'] instanceof String)) {
            throw new Error("Expected the field `cylinder_material_code` to be a primitive type in the JSON string but got " + data['cylinder_material_code']);
        }
        // ensure the json data is a string
        if (data['cylinder_serial'] && !(typeof data['cylinder_serial'] === 'string' || data['cylinder_serial'] instanceof String)) {
            throw new Error("Expected the field `cylinder_serial` to be a primitive type in the JSON string but got " + data['cylinder_serial']);
        }
        // ensure the json data is a string
        if (data['printer_material_code'] && !(typeof data['printer_material_code'] === 'string' || data['printer_material_code'] instanceof String)) {
            throw new Error("Expected the field `printer_material_code` to be a primitive type in the JSON string but got " + data['printer_material_code']);
        }

        return true;
    }


}

Fuse11Printer.RequiredProperties = ["id", "product_name", "status", "is_connected", "connection_type", "ip_address", "firmware_version", "is_remote_print_enabled", "estimated_print_time_remaining_ms", "bed_temperature_c", "powder_level", "printing_layer", "printing_guid", "cylinder_material_code", "cylinder_serial", "printer_material_code", "powder_credit_g"];

/**
 * @member {String} id
 */
Fuse11Printer.prototype['id'] = undefined;

/**
 * @member {String} product_name
 */
Fuse11Printer.prototype['product_name'] = undefined;

/**
 * @member {String} status
 */
Fuse11Printer.prototype['status'] = undefined;

/**
 * @member {Boolean} is_connected
 */
Fuse11Printer.prototype['is_connected'] = undefined;

/**
 * @member {module:model/Fuse11Printer.ConnectionTypeEnum} connection_type
 */
Fuse11Printer.prototype['connection_type'] = undefined;

/**
 * @member {String} ip_address
 */
Fuse11Printer.prototype['ip_address'] = undefined;

/**
 * @member {String} firmware_version
 */
Fuse11Printer.prototype['firmware_version'] = undefined;

/**
 * @member {Boolean} is_remote_print_enabled
 */
Fuse11Printer.prototype['is_remote_print_enabled'] = undefined;

/**
 * @member {Number} estimated_print_time_remaining_ms
 */
Fuse11Printer.prototype['estimated_print_time_remaining_ms'] = undefined;

/**
 * @member {Number} bed_temperature_c
 */
Fuse11Printer.prototype['bed_temperature_c'] = undefined;

/**
 * @member {String} powder_level
 */
Fuse11Printer.prototype['powder_level'] = undefined;

/**
 * @member {Number} printing_layer
 */
Fuse11Printer.prototype['printing_layer'] = undefined;

/**
 * @member {String} printing_guid
 */
Fuse11Printer.prototype['printing_guid'] = undefined;

/**
 * @member {String} cylinder_material_code
 */
Fuse11Printer.prototype['cylinder_material_code'] = undefined;

/**
 * @member {String} cylinder_serial
 */
Fuse11Printer.prototype['cylinder_serial'] = undefined;

/**
 * @member {String} printer_material_code
 */
Fuse11Printer.prototype['printer_material_code'] = undefined;

/**
 * @member {Number} powder_credit_g
 */
Fuse11Printer.prototype['powder_credit_g'] = undefined;





/**
 * Allowed values for the <code>connection_type</code> property.
 * @enum {String}
 * @readonly
 */
Fuse11Printer['ConnectionTypeEnum'] = {

    /**
     * value: "UNKNOWN"
     * @const
     */
    "UNKNOWN": "UNKNOWN",

    /**
     * value: "VIRTUAL"
     * @const
     */
    "VIRTUAL": "VIRTUAL",

    /**
     * value: "REMOTE"
     * @const
     */
    "REMOTE": "REMOTE",

    /**
     * value: "USB"
     * @const
     */
    "USB": "USB",

    /**
     * value: "WIFI"
     * @const
     */
    "WIFI": "WIFI",

    /**
     * value: "ETHERNET"
     * @const
     */
    "ETHERNET": "ETHERNET",

    /**
     * value: ""
     * @const
     */
    "empty": ""
};



export default Fuse11Printer;

