/**
 * PreForm API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GenericDevice model module.
 * @module model/GenericDevice
 * @version 1.0
 */
class GenericDevice {
    /**
     * Constructs a new <code>GenericDevice</code>.
     * @alias module:model/GenericDevice
     * @param id {String} 
     * @param productName {String} 
     * @param status {String} 
     * @param isConnected {Boolean} 
     * @param connectionType {module:model/GenericDevice.ConnectionTypeEnum} 
     * @param ipAddress {String} 
     * @param firmwareVersion {String} 
     */
    constructor(id, productName, status, isConnected, connectionType, ipAddress, firmwareVersion) { 
        
        GenericDevice.initialize(this, id, productName, status, isConnected, connectionType, ipAddress, firmwareVersion);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, productName, status, isConnected, connectionType, ipAddress, firmwareVersion) { 
        obj['id'] = id;
        obj['product_name'] = productName;
        obj['status'] = status;
        obj['is_connected'] = isConnected;
        obj['connection_type'] = connectionType;
        obj['ip_address'] = ipAddress;
        obj['firmware_version'] = firmwareVersion;
    }

    /**
     * Constructs a <code>GenericDevice</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GenericDevice} obj Optional instance to populate.
     * @return {module:model/GenericDevice} The populated <code>GenericDevice</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GenericDevice();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('product_name')) {
                obj['product_name'] = ApiClient.convertToType(data['product_name'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('is_connected')) {
                obj['is_connected'] = ApiClient.convertToType(data['is_connected'], 'Boolean');
            }
            if (data.hasOwnProperty('connection_type')) {
                obj['connection_type'] = ApiClient.convertToType(data['connection_type'], 'String');
            }
            if (data.hasOwnProperty('ip_address')) {
                obj['ip_address'] = ApiClient.convertToType(data['ip_address'], 'String');
            }
            if (data.hasOwnProperty('firmware_version')) {
                obj['firmware_version'] = ApiClient.convertToType(data['firmware_version'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GenericDevice</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GenericDevice</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of GenericDevice.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['product_name'] && !(typeof data['product_name'] === 'string' || data['product_name'] instanceof String)) {
            throw new Error("Expected the field `product_name` to be a primitive type in the JSON string but got " + data['product_name']);
        }
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }
        // ensure the json data is a string
        if (data['connection_type'] && !(typeof data['connection_type'] === 'string' || data['connection_type'] instanceof String)) {
            throw new Error("Expected the field `connection_type` to be a primitive type in the JSON string but got " + data['connection_type']);
        }
        // ensure the json data is a string
        if (data['ip_address'] && !(typeof data['ip_address'] === 'string' || data['ip_address'] instanceof String)) {
            throw new Error("Expected the field `ip_address` to be a primitive type in the JSON string but got " + data['ip_address']);
        }
        // ensure the json data is a string
        if (data['firmware_version'] && !(typeof data['firmware_version'] === 'string' || data['firmware_version'] instanceof String)) {
            throw new Error("Expected the field `firmware_version` to be a primitive type in the JSON string but got " + data['firmware_version']);
        }

        return true;
    }


}

GenericDevice.RequiredProperties = ["id", "product_name", "status", "is_connected", "connection_type", "ip_address", "firmware_version"];

/**
 * @member {String} id
 */
GenericDevice.prototype['id'] = undefined;

/**
 * @member {String} product_name
 */
GenericDevice.prototype['product_name'] = undefined;

/**
 * @member {String} status
 */
GenericDevice.prototype['status'] = undefined;

/**
 * @member {Boolean} is_connected
 */
GenericDevice.prototype['is_connected'] = undefined;

/**
 * @member {module:model/GenericDevice.ConnectionTypeEnum} connection_type
 */
GenericDevice.prototype['connection_type'] = undefined;

/**
 * @member {String} ip_address
 */
GenericDevice.prototype['ip_address'] = undefined;

/**
 * @member {String} firmware_version
 */
GenericDevice.prototype['firmware_version'] = undefined;





/**
 * Allowed values for the <code>connection_type</code> property.
 * @enum {String}
 * @readonly
 */
GenericDevice['ConnectionTypeEnum'] = {

    /**
     * value: "UNKNOWN"
     * @const
     */
    "UNKNOWN": "UNKNOWN",

    /**
     * value: "VIRTUAL"
     * @const
     */
    "VIRTUAL": "VIRTUAL",

    /**
     * value: "REMOTE"
     * @const
     */
    "REMOTE": "REMOTE",

    /**
     * value: "USB"
     * @const
     */
    "USB": "USB",

    /**
     * value: "WIFI"
     * @const
     */
    "WIFI": "WIFI",

    /**
     * value: "ETHERNET"
     * @const
     */
    "ETHERNET": "ETHERNET",

    /**
     * value: ""
     * @const
     */
    "empty": ""
};



export default GenericDevice;

