/**
 * PreForm API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AccessToken from './AccessToken';
import UsernameAndPassword from './UsernameAndPassword';

/**
 * The LoginPostRequest model module.
 * @module model/LoginPostRequest
 * @version 1.0
 */
class LoginPostRequest {
    /**
     * Constructs a new <code>LoginPostRequest</code>.
     * @alias module:model/LoginPostRequest
     * @param {(module:model/AccessToken|module:model/UsernameAndPassword)} instance The actual instance to initialize LoginPostRequest.
     */
    constructor(instance = null) {
        if (instance === null) {
            this.actualInstance = null;
            return;
        }
        var match = 0;
        var errorMessages = [];
        try {
            if (typeof instance === "UsernameAndPassword") {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                UsernameAndPassword.validateJSON(instance); // throw an exception if no match
                // create UsernameAndPassword from JS object
                this.actualInstance = UsernameAndPassword.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into UsernameAndPassword
            errorMessages.push("Failed to construct UsernameAndPassword: " + err)
        }

        try {
            if (typeof instance === "AccessToken") {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                AccessToken.validateJSON(instance); // throw an exception if no match
                // create AccessToken from JS object
                this.actualInstance = AccessToken.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into AccessToken
            errorMessages.push("Failed to construct AccessToken: " + err)
        }

        if (match > 1) {
            throw new Error("Multiple matches found constructing `LoginPostRequest` with oneOf schemas AccessToken, UsernameAndPassword. Input: " + JSON.stringify(instance));
        } else if (match === 0) {
            this.actualInstance = null; // clear the actual instance in case there are multiple matches
            throw new Error("No match found constructing `LoginPostRequest` with oneOf schemas AccessToken, UsernameAndPassword. Details: " +
                            errorMessages.join(", "));
        } else { // only 1 match
            // the input is valid
        }
    }

    /**
     * Constructs a <code>LoginPostRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LoginPostRequest} obj Optional instance to populate.
     * @return {module:model/LoginPostRequest} The populated <code>LoginPostRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        return new LoginPostRequest(data);
    }

    /**
     * Gets the actual instance, which can be <code>AccessToken</code>, <code>UsernameAndPassword</code>.
     * @return {(module:model/AccessToken|module:model/UsernameAndPassword)} The actual instance.
     */
    getActualInstance() {
        return this.actualInstance;
    }

    /**
     * Sets the actual instance, which can be <code>AccessToken</code>, <code>UsernameAndPassword</code>.
     * @param {(module:model/AccessToken|module:model/UsernameAndPassword)} obj The actual instance.
     */
    setActualInstance(obj) {
       this.actualInstance = LoginPostRequest.constructFromObject(obj).getActualInstance();
    }

    /**
     * Returns the JSON representation of the actual instance.
     * @return {string}
     */
    toJSON = function(){
        return this.getActualInstance();
    }

    /**
     * Create an instance of LoginPostRequest from a JSON string.
     * @param {string} json_string JSON string.
     * @return {module:model/LoginPostRequest} An instance of LoginPostRequest.
     */
    static fromJSON = function(json_string){
        return LoginPostRequest.constructFromObject(JSON.parse(json_string));
    }
}

/**
 * @member {String} username
 */
LoginPostRequest.prototype['username'] = undefined;

/**
 * @member {String} password
 */
LoginPostRequest.prototype['password'] = undefined;

/**
 * @member {String} access_token
 */
LoginPostRequest.prototype['access_token'] = undefined;


LoginPostRequest.OneOf = ["AccessToken", "UsernameAndPassword"];

export default LoginPostRequest;

