/**
 * PreForm API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ScenePositionModel from './ScenePositionModel';

/**
 * The ModelPropertiesBbox model module.
 * @module model/ModelPropertiesBbox
 * @version 1.0
 */
class ModelPropertiesBbox {
    /**
     * Constructs a new <code>ModelPropertiesBbox</code>.
     * @alias module:model/ModelPropertiesBbox
     */
    constructor() { 
        
        ModelPropertiesBbox.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ModelPropertiesBbox</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ModelPropertiesBbox} obj Optional instance to populate.
     * @return {module:model/ModelPropertiesBbox} The populated <code>ModelPropertiesBbox</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ModelPropertiesBbox();

            if (data.hasOwnProperty('min_corner')) {
                obj['min_corner'] = ScenePositionModel.constructFromObject(data['min_corner']);
            }
            if (data.hasOwnProperty('max_corner')) {
                obj['max_corner'] = ScenePositionModel.constructFromObject(data['max_corner']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ModelPropertiesBbox</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ModelPropertiesBbox</code>.
     */
    static validateJSON(data) {
        // validate the optional field `min_corner`
        if (data['min_corner']) { // data not null
          ScenePositionModel.validateJSON(data['min_corner']);
        }
        // validate the optional field `max_corner`
        if (data['max_corner']) { // data not null
          ScenePositionModel.validateJSON(data['max_corner']);
        }

        return true;
    }


}



/**
 * @member {module:model/ScenePositionModel} min_corner
 */
ModelPropertiesBbox.prototype['min_corner'] = undefined;

/**
 * @member {module:model/ScenePositionModel} max_corner
 */
ModelPropertiesBbox.prototype['max_corner'] = undefined;






export default ModelPropertiesBbox;

