/**
 * PreForm API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PrintValidationResultModelPerModelResultsValue model module.
 * @module model/PrintValidationResultModelPerModelResultsValue
 * @version 1.0
 */
class PrintValidationResultModelPerModelResultsValue {
    /**
     * Constructs a new <code>PrintValidationResultModelPerModelResultsValue</code>.
     * @alias module:model/PrintValidationResultModelPerModelResultsValue
     */
    constructor() { 
        
        PrintValidationResultModelPerModelResultsValue.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PrintValidationResultModelPerModelResultsValue</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PrintValidationResultModelPerModelResultsValue} obj Optional instance to populate.
     * @return {module:model/PrintValidationResultModelPerModelResultsValue} The populated <code>PrintValidationResultModelPerModelResultsValue</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PrintValidationResultModelPerModelResultsValue();

            if (data.hasOwnProperty('cups')) {
                obj['cups'] = ApiClient.convertToType(data['cups'], 'Number');
            }
            if (data.hasOwnProperty('unsupported_minima')) {
                obj['unsupported_minima'] = ApiClient.convertToType(data['unsupported_minima'], 'Number');
            }
            if (data.hasOwnProperty('undersupported')) {
                obj['undersupported'] = ApiClient.convertToType(data['undersupported'], 'Boolean');
            }
            if (data.hasOwnProperty('has_seamline')) {
                obj['has_seamline'] = ApiClient.convertToType(data['has_seamline'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PrintValidationResultModelPerModelResultsValue</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PrintValidationResultModelPerModelResultsValue</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * The number of cups in the model
 * @member {Number} cups
 */
PrintValidationResultModelPerModelResultsValue.prototype['cups'] = undefined;

/**
 * The number of unsupported minima in the model
 * @member {Number} unsupported_minima
 */
PrintValidationResultModelPerModelResultsValue.prototype['unsupported_minima'] = undefined;

/**
 * Whether the model is undersupported
 * @member {Boolean} undersupported
 */
PrintValidationResultModelPerModelResultsValue.prototype['undersupported'] = undefined;

/**
 * Whether the model has a seamline
 * @member {Boolean} has_seamline
 */
PrintValidationResultModelPerModelResultsValue.prototype['has_seamline'] = undefined;






export default PrintValidationResultModelPerModelResultsValue;

