/**
 * PreForm API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PrintValidationResultModelPerModelResultsValue from './PrintValidationResultModelPerModelResultsValue';

/**
 * The PrintValidationResultModel model module.
 * @module model/PrintValidationResultModel
 * @version 1.0
 */
class PrintValidationResultModel {
    /**
     * Constructs a new <code>PrintValidationResultModel</code>.
     * @alias module:model/PrintValidationResultModel
     */
    constructor() { 
        
        PrintValidationResultModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PrintValidationResultModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PrintValidationResultModel} obj Optional instance to populate.
     * @return {module:model/PrintValidationResultModel} The populated <code>PrintValidationResultModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PrintValidationResultModel();

            if (data.hasOwnProperty('per_model_results')) {
                obj['per_model_results'] = ApiClient.convertToType(data['per_model_results'], {'String': PrintValidationResultModelPerModelResultsValue});
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PrintValidationResultModel</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PrintValidationResultModel</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * A map of model IDs to their print validation results.
 * @member {Object.<String, module:model/PrintValidationResultModelPerModelResultsValue>} per_model_results
 */
PrintValidationResultModel.prototype['per_model_results'] = undefined;






export default PrintValidationResultModel;

