/**
 * PreForm API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Default from './Default';
import DentalMode from './DentalMode';
import ModelsSelectionModel from './ModelsSelectionModel';

/**
 * The SceneAutoOrientPostRequest model module.
 * @module model/SceneAutoOrientPostRequest
 * @version 1.0
 */
class SceneAutoOrientPostRequest {
    /**
     * Constructs a new <code>SceneAutoOrientPostRequest</code>.
     * @alias module:model/SceneAutoOrientPostRequest
     * @param {(module:model/Default|module:model/DentalMode)} instance The actual instance to initialize SceneAutoOrientPostRequest.
     */
    constructor(instance = null) {
        if (instance === null) {
            this.actualInstance = null;
            return;
        }
        var match = 0;
        var errorMessages = [];
        try {
            if (typeof instance === "Default") {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                Default.validateJSON(instance); // throw an exception if no match
                // create Default from JS object
                this.actualInstance = Default.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into Default
            errorMessages.push("Failed to construct Default: " + err)
        }

        try {
            if (typeof instance === "DentalMode") {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                DentalMode.validateJSON(instance); // throw an exception if no match
                // create DentalMode from JS object
                this.actualInstance = DentalMode.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into DentalMode
            errorMessages.push("Failed to construct DentalMode: " + err)
        }

        if (match > 1) {
            throw new Error("Multiple matches found constructing `SceneAutoOrientPostRequest` with oneOf schemas Default, DentalMode. Input: " + JSON.stringify(instance));
        } else if (match === 0) {
            this.actualInstance = null; // clear the actual instance in case there are multiple matches
            throw new Error("No match found constructing `SceneAutoOrientPostRequest` with oneOf schemas Default, DentalMode. Details: " +
                            errorMessages.join(", "));
        } else { // only 1 match
            // the input is valid
        }
    }

    /**
     * Constructs a <code>SceneAutoOrientPostRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SceneAutoOrientPostRequest} obj Optional instance to populate.
     * @return {module:model/SceneAutoOrientPostRequest} The populated <code>SceneAutoOrientPostRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        return new SceneAutoOrientPostRequest(data);
    }

    /**
     * Gets the actual instance, which can be <code>Default</code>, <code>DentalMode</code>.
     * @return {(module:model/Default|module:model/DentalMode)} The actual instance.
     */
    getActualInstance() {
        return this.actualInstance;
    }

    /**
     * Sets the actual instance, which can be <code>Default</code>, <code>DentalMode</code>.
     * @param {(module:model/Default|module:model/DentalMode)} obj The actual instance.
     */
    setActualInstance(obj) {
       this.actualInstance = SceneAutoOrientPostRequest.constructFromObject(obj).getActualInstance();
    }

    /**
     * Returns the JSON representation of the actual instance.
     * @return {string}
     */
    toJSON = function(){
        return this.getActualInstance();
    }

    /**
     * Create an instance of SceneAutoOrientPostRequest from a JSON string.
     * @param {string} json_string JSON string.
     * @return {module:model/SceneAutoOrientPostRequest} An instance of SceneAutoOrientPostRequest.
     */
    static fromJSON = function(json_string){
        return SceneAutoOrientPostRequest.constructFromObject(JSON.parse(json_string));
    }
}

/**
 * @member {module:model/ModelsSelectionModel} models
 */
SceneAutoOrientPostRequest.prototype['models'] = undefined;

/**
 * @member {module:model/SceneAutoOrientPostRequest.ModeEnum} mode
 */
SceneAutoOrientPostRequest.prototype['mode'] = undefined;

/**
 * Degrees of tilt. Only applies to the DENTAL mode
 * @member {Number} tilt
 */
SceneAutoOrientPostRequest.prototype['tilt'] = undefined;


SceneAutoOrientPostRequest.OneOf = ["Default", "DentalMode"];

export default SceneAutoOrientPostRequest;

