/**
 * PreForm API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SceneAutoPackPostRequest model module.
 * @module model/SceneAutoPackPostRequest
 * @version 1.0
 */
class SceneAutoPackPostRequest {
    /**
     * Constructs a new <code>SceneAutoPackPostRequest</code>.
     * @alias module:model/SceneAutoPackPostRequest
     */
    constructor() { 
        
        SceneAutoPackPostRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SceneAutoPackPostRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SceneAutoPackPostRequest} obj Optional instance to populate.
     * @return {module:model/SceneAutoPackPostRequest} The populated <code>SceneAutoPackPostRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SceneAutoPackPostRequest();

            if (data.hasOwnProperty('model_spacing_mm')) {
                obj['model_spacing_mm'] = ApiClient.convertToType(data['model_spacing_mm'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SceneAutoPackPostRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SceneAutoPackPostRequest</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Number} model_spacing_mm
 */
SceneAutoPackPostRequest.prototype['model_spacing_mm'] = undefined;






export default SceneAutoPackPostRequest;

