/**
 * PreForm API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import RepairBehaviorModel from './RepairBehaviorModel';

/**
 * The SceneModelsIdReplacePostRequest model module.
 * @module model/SceneModelsIdReplacePostRequest
 * @version 1.0
 */
class SceneModelsIdReplacePostRequest {
    /**
     * Constructs a new <code>SceneModelsIdReplacePostRequest</code>.
     * @alias module:model/SceneModelsIdReplacePostRequest
     */
    constructor() { 
        
        SceneModelsIdReplacePostRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SceneModelsIdReplacePostRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SceneModelsIdReplacePostRequest} obj Optional instance to populate.
     * @return {module:model/SceneModelsIdReplacePostRequest} The populated <code>SceneModelsIdReplacePostRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SceneModelsIdReplacePostRequest();

            if (data.hasOwnProperty('file')) {
                obj['file'] = ApiClient.convertToType(data['file'], 'String');
            }
            if (data.hasOwnProperty('repair_behavior')) {
                obj['repair_behavior'] = RepairBehaviorModel.constructFromObject(data['repair_behavior']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SceneModelsIdReplacePostRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SceneModelsIdReplacePostRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['file'] && !(typeof data['file'] === 'string' || data['file'] instanceof String)) {
            throw new Error("Expected the field `file` to be a primitive type in the JSON string but got " + data['file']);
        }

        return true;
    }


}



/**
 * Full path to the file to load
 * @member {String} file
 */
SceneModelsIdReplacePostRequest.prototype['file'] = undefined;

/**
 * @member {module:model/RepairBehaviorModel} repair_behavior
 */
SceneModelsIdReplacePostRequest.prototype['repair_behavior'] = undefined;






export default SceneModelsIdReplacePostRequest;

