/**
 * PreForm API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ModelProperties from './ModelProperties';

/**
 * The SceneModelsIdReplacePost200Response model module.
 * @module model/SceneModelsIdReplacePost200Response
 * @version 1.0
 */
class SceneModelsIdReplacePost200Response {
    /**
     * Constructs a new <code>SceneModelsIdReplacePost200Response</code>.
     * @alias module:model/SceneModelsIdReplacePost200Response
     */
    constructor() { 
        
        SceneModelsIdReplacePost200Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SceneModelsIdReplacePost200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SceneModelsIdReplacePost200Response} obj Optional instance to populate.
     * @return {module:model/SceneModelsIdReplacePost200Response} The populated <code>SceneModelsIdReplacePost200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SceneModelsIdReplacePost200Response();

            if (data.hasOwnProperty('warnings')) {
                obj['warnings'] = ApiClient.convertToType(data['warnings'], ['String']);
            }
            if (data.hasOwnProperty('model_properties')) {
                obj['model_properties'] = ModelProperties.constructFromObject(data['model_properties']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SceneModelsIdReplacePost200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SceneModelsIdReplacePost200Response</code>.
     */
    static validateJSON(data) {
        // ensure the json data is an array
        if (!Array.isArray(data['warnings'])) {
            throw new Error("Expected the field `warnings` to be an array in the JSON data but got " + data['warnings']);
        }
        // validate the optional field `model_properties`
        if (data['model_properties']) { // data not null
          ModelProperties.validateJSON(data['model_properties']);
        }

        return true;
    }


}



/**
 * @member {Array.<String>} warnings
 */
SceneModelsIdReplacePost200Response.prototype['warnings'] = undefined;

/**
 * @member {module:model/ModelProperties} model_properties
 */
SceneModelsIdReplacePost200Response.prototype['model_properties'] = undefined;






export default SceneModelsIdReplacePost200Response;

