/**
 * PreForm API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import OrientationModel from './OrientationModel';
import ScenePositionModel from './ScenePositionModel';
import UnitsModel from './UnitsModel';

/**
 * The SceneModelsIdPostRequest model module.
 * @module model/SceneModelsIdPostRequest
 * @version 1.0
 */
class SceneModelsIdPostRequest {
    /**
     * Constructs a new <code>SceneModelsIdPostRequest</code>.
     * @alias module:model/SceneModelsIdPostRequest
     */
    constructor() { 
        
        SceneModelsIdPostRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SceneModelsIdPostRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SceneModelsIdPostRequest} obj Optional instance to populate.
     * @return {module:model/SceneModelsIdPostRequest} The populated <code>SceneModelsIdPostRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SceneModelsIdPostRequest();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('position')) {
                obj['position'] = ScenePositionModel.constructFromObject(data['position']);
            }
            if (data.hasOwnProperty('orientation')) {
                obj['orientation'] = OrientationModel.constructFromObject(data['orientation']);
            }
            if (data.hasOwnProperty('scale')) {
                obj['scale'] = ApiClient.convertToType(data['scale'], 'Number');
            }
            if (data.hasOwnProperty('units')) {
                obj['units'] = UnitsModel.constructFromObject(data['units']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SceneModelsIdPostRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SceneModelsIdPostRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // validate the optional field `position`
        if (data['position']) { // data not null
          ScenePositionModel.validateJSON(data['position']);
        }
        // validate the optional field `orientation`
        if (data['orientation']) { // data not null
          OrientationModel.validateJSON(data['orientation']);
        }

        return true;
    }


}



/**
 * The name of the model used within job preparation.
 * @member {String} name
 */
SceneModelsIdPostRequest.prototype['name'] = undefined;

/**
 * @member {module:model/ScenePositionModel} position
 */
SceneModelsIdPostRequest.prototype['position'] = undefined;

/**
 * @member {module:model/OrientationModel} orientation
 */
SceneModelsIdPostRequest.prototype['orientation'] = undefined;

/**
 * The scale factor to apply to the model
 * @member {Number} scale
 */
SceneModelsIdPostRequest.prototype['scale'] = undefined;

/**
 * @member {module:model/UnitsModel} units
 */
SceneModelsIdPostRequest.prototype['units'] = undefined;






export default SceneModelsIdPostRequest;

