/**
 * PreForm API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SLA model module.
 * @module model/SLA
 * @version 1.0
 */
class SLA {
    /**
     * Constructs a new <code>SLA</code>.
     * @alias module:model/SLA
     */
    constructor() { 
        
        SLA.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SLA</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SLA} obj Optional instance to populate.
     * @return {module:model/SLA} The populated <code>SLA</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SLA();

            if (data.hasOwnProperty('volume_ml')) {
                obj['volume_ml'] = ApiClient.convertToType(data['volume_ml'], 'Number');
            }
            if (data.hasOwnProperty('unsupported_volume_ml')) {
                obj['unsupported_volume_ml'] = ApiClient.convertToType(data['unsupported_volume_ml'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SLA</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SLA</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * The total volume of models and supports in the scene
 * @member {Number} volume_ml
 */
SLA.prototype['volume_ml'] = undefined;

/**
 * The total volume of models in the scene
 * @member {Number} unsupported_volume_ml
 */
SLA.prototype['unsupported_volume_ml'] = undefined;






export default SLA;

