/**
 * PreForm API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SLS model module.
 * @module model/SLS
 * @version 1.0
 */
class SLS {
    /**
     * Constructs a new <code>SLS</code>.
     * @alias module:model/SLS
     */
    constructor() { 
        
        SLS.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SLS</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SLS} obj Optional instance to populate.
     * @return {module:model/SLS} The populated <code>SLS</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SLS();

            if (data.hasOwnProperty('total_powder_ml')) {
                obj['total_powder_ml'] = ApiClient.convertToType(data['total_powder_ml'], 'Number');
            }
            if (data.hasOwnProperty('total_powder_kg')) {
                obj['total_powder_kg'] = ApiClient.convertToType(data['total_powder_kg'], 'Number');
            }
            if (data.hasOwnProperty('total_sintered_powder_ml')) {
                obj['total_sintered_powder_ml'] = ApiClient.convertToType(data['total_sintered_powder_ml'], 'Number');
            }
            if (data.hasOwnProperty('total_sintered_powder_kg')) {
                obj['total_sintered_powder_kg'] = ApiClient.convertToType(data['total_sintered_powder_kg'], 'Number');
            }
            if (data.hasOwnProperty('mass_packing_density')) {
                obj['mass_packing_density'] = ApiClient.convertToType(data['mass_packing_density'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SLS</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SLS</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Number} total_powder_ml
 */
SLS.prototype['total_powder_ml'] = undefined;

/**
 * @member {Number} total_powder_kg
 */
SLS.prototype['total_powder_kg'] = undefined;

/**
 * @member {Number} total_sintered_powder_ml
 */
SLS.prototype['total_sintered_powder_ml'] = undefined;

/**
 * @member {Number} total_sintered_powder_kg
 */
SLS.prototype['total_sintered_powder_kg'] = undefined;

/**
 * @member {Number} mass_packing_density
 */
SLS.prototype['mass_packing_density'] = undefined;






export default SLS;

