/**
 * PreForm API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TransformMatrixModel model module.
 * @module model/TransformMatrixModel
 * @version 1.0
 */
class TransformMatrixModel {
    /**
     * Constructs a new <code>TransformMatrixModel</code>.
     * Orientation specified a 3x3 matrix, the linear component of a 3D rigid transform.
     * @alias module:model/TransformMatrixModel
     * @param linear {Array.<Array.<Number>>} 
     */
    constructor(linear) { 
        
        TransformMatrixModel.initialize(this, linear);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, linear) { 
        obj['linear'] = linear;
    }

    /**
     * Constructs a <code>TransformMatrixModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TransformMatrixModel} obj Optional instance to populate.
     * @return {module:model/TransformMatrixModel} The populated <code>TransformMatrixModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TransformMatrixModel();

            if (data.hasOwnProperty('linear')) {
                obj['linear'] = ApiClient.convertToType(data['linear'], [['Number']]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TransformMatrixModel</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TransformMatrixModel</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of TransformMatrixModel.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is an array
        if (!Array.isArray(data['linear'])) {
            throw new Error("Expected the field `linear` to be an array in the JSON data but got " + data['linear']);
        }

        return true;
    }


}

TransformMatrixModel.RequiredProperties = ["linear"];

/**
 * @member {Array.<Array.<Number>>} linear
 */
TransformMatrixModel.prototype['linear'] = undefined;






export default TransformMatrixModel;

