/**
 * PreForm API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PreFormApi);
  }
}(this, function(expect, PreFormApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PreFormApi.FleetControlPrinterGroup();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('FleetControlPrinterGroup', function() {
    it('should create an instance of FleetControlPrinterGroup', function() {
      // uncomment below and update the code to test FleetControlPrinterGroup
      //var instance = new PreFormApi.FleetControlPrinterGroup();
      //expect(instance).to.be.a(PreFormApi.FleetControlPrinterGroup);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new PreFormApi.FleetControlPrinterGroup();
      //expect(instance).to.be();
    });

    it('should have the property productName (base name: "product_name")', function() {
      // uncomment below and update the code to test the property productName
      //var instance = new PreFormApi.FleetControlPrinterGroup();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instance = new PreFormApi.FleetControlPrinterGroup();
      //expect(instance).to.be();
    });

    it('should have the property isConnected (base name: "is_connected")', function() {
      // uncomment below and update the code to test the property isConnected
      //var instance = new PreFormApi.FleetControlPrinterGroup();
      //expect(instance).to.be();
    });

    it('should have the property connectionType (base name: "connection_type")', function() {
      // uncomment below and update the code to test the property connectionType
      //var instance = new PreFormApi.FleetControlPrinterGroup();
      //expect(instance).to.be();
    });

    it('should have the property firmwareVersion (base name: "firmware_version")', function() {
      // uncomment below and update the code to test the property firmwareVersion
      //var instance = new PreFormApi.FleetControlPrinterGroup();
      //expect(instance).to.be();
    });

    it('should have the property dashboardGroupId (base name: "dashboard_group_id")', function() {
      // uncomment below and update the code to test the property dashboardGroupId
      //var instance = new PreFormApi.FleetControlPrinterGroup();
      //expect(instance).to.be();
    });

    it('should have the property dashboardQueueId (base name: "dashboard_queue_id")', function() {
      // uncomment below and update the code to test the property dashboardQueueId
      //var instance = new PreFormApi.FleetControlPrinterGroup();
      //expect(instance).to.be();
    });

  });

}));
