/**
 * PreForm API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PreFormApi);
  }
}(this, function(expect, PreFormApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PreFormApi.ScenePrintPostRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ScenePrintPostRequest', function() {
    it('should create an instance of ScenePrintPostRequest', function() {
      // uncomment below and update the code to test ScenePrintPostRequest
      //var instance = new PreFormApi.ScenePrintPostRequest();
      //expect(instance).to.be.a(PreFormApi.ScenePrintPostRequest);
    });

    it('should have the property printer (base name: "printer")', function() {
      // uncomment below and update the code to test the property printer
      //var instance = new PreFormApi.ScenePrintPostRequest();
      //expect(instance).to.be();
    });

    it('should have the property jobName (base name: "job_name")', function() {
      // uncomment below and update the code to test the property jobName
      //var instance = new PreFormApi.ScenePrintPostRequest();
      //expect(instance).to.be();
    });

  });

}));
