templateDir: python/generator_custom_templates
additionalProperties:
  projectName: formlabs-sdk
  packageName: formlabs
files:
  PreFormApi.py:
    folder: formlabs
    destinationFilename: PreFormApi.py
    templateType: SupportingFiles
  __init__package.mustache:
    # Overring the default template:
    # https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/python/__init__package.mustache
    # to add an import of the PreFormApi.py
    folder: formlabs
    destinationFilename: __init__.py
    templateType: SupportingFiles
